import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';

const engine = await readFile('src/itransliterator.js', 'utf8');
const component = await readFile('src/itextarea.js', 'utf8');
const bundledEngine = engine.replace('export function createTransliterator', 'function createTransliterator');
const bundledComponent = component
  .replace("import { createTransliterator } from './itransliterator.js';\n\n", '')
  .replace('export function configureITranslator', 'function configureITranslator')
  .replace('export function setITranslatorTarget', 'function setITranslatorTarget')
  .replace('export function setITranslatorFont', 'function setITranslatorFont')
  .replace('export function setITranslatorFontSize', 'function setITranslatorFontSize')
  .replace('export class ITranslatorTextarea', 'class ITranslatorTextarea');

const css = await readFile('src/itextarea.css', 'utf8');
const config = await readFile('config/itrans-config.json', 'utf8');
const fontFiles = [
  'NotoSansDevanagari-Regular.ttf',
  'NotoSerifDevanagari-Regular.ttf',
  'TiroDevanagariSanskrit-Regular.ttf',
  'Sanskrit-2003-Font.ttf',
  'Chandas_Font.ttf',
  'OFL-Noto-Sans-Devanagari.txt',
  'OFL-Noto-Serif-Devanagari.txt',
  'OFL-Tiro-Devanagari-Sanskrit.txt',
  'LICENSE-Sanskrit-2003.txt',
  'LICENSE-Chandas-GPL-2.0.txt',
];

await mkdir('dist/fonts', { recursive: true });
await writeFile('dist/itarea.js', `/* iTranslator Text Area | generated by npm run build */\n${bundledEngine}\n${bundledComponent}\nexport { configureITranslator, setITranslatorTarget, setITranslatorFont, setITranslatorFontSize, ITranslatorTextarea };\n`);
await writeFile('dist/itarea-standalone.js', `/* iTranslator Text Area standalone build | generated by npm run build */\n${bundledEngine}\n${bundledComponent}\nconfigureITranslator(${config.trim()});\n`);
await writeFile('dist/itarea.css', css.replaceAll('../fonts/', './fonts/'));
await writeFile('dist/itrans-config.json', config);
await writeFile('dist/itrans-config.js', `/* iTranslator Text Area configuration | generated by npm run build */\nexport default ${config.trim()};\n`);
await Promise.all(fontFiles.map(file => copyFile(`fonts/${file}`, `dist/fonts/${file}`)));
