import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';

const engine = await readFile('src/itransliterator.js', 'utf8');
const component = await readFile('src/itextarea.js', 'utf8');
const bundledEngine = engine.replace('export function createTransliterator', 'function createTransliterator');
const bundledComponent = component
  .replace("import { createTransliterator } from './itransliterator.js';\n\n", '')
  .replace('export function configureITranslator', 'function configureITranslator')
  .replace('export function setITranslatorTarget', 'function setITranslatorTarget')
  .replace('export class ITranslatorTextarea', 'class ITranslatorTextarea');

await mkdir('dist', { recursive: true });
await writeFile('dist/itarea.js', `/* iTranslator Text Area | generated by npm run build */\n${bundledEngine}\n${bundledComponent}\nexport { configureITranslator, setITranslatorTarget, ITranslatorTextarea };\n`);
await copyFile('src/itextarea.css', 'dist/itarea.css');
await copyFile('config/itrans-config.json', 'dist/itrans-config.json');
