import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';

const engine = await readFile('src/itransliterator.js', 'utf8');
const audio = await readFile('src/itaudio.js', 'utf8');
const documentModule = await readFile('src/itdocument.js', 'utf8');
const richText = await readFile('src/itrichtext.js', 'utf8');
const component = await readFile('src/itextarea.js', 'utf8');
const bundledEngine = engine.replace('export function createTransliterator', 'function createTransliterator');
const bundledAudio = audio
  .replace('export const audioIcons', 'const audioIcons')
  .replace('export function audioDialogMarkup', 'function audioDialogMarkup')
  .replace('export function createAudioController', 'function createAudioController');
const bundledDocument = documentModule
  .replace('export const documentIcons', 'const documentIcons')
  .replace('export async function createItareaArchive', 'async function createItareaArchive')
  .replace('export async function readItareaArchive', 'async function readItareaArchive')
  .replace('export function createDocumentController', 'function createDocumentController');
const bundledRichText = richText
  .replace('export function richTextToolbarMarkup', 'function richTextToolbarMarkup')
  .replace('export function sanitizeRichHtml', 'function sanitizeRichHtml')
  .replace('export function createRichTextController', 'function createRichTextController');
const bundledComponent = component
  .replace("import { createTransliterator } from './itransliterator.js';\n", '')
  .replace("import { audioDialogMarkup, audioIcons, createAudioController } from './itaudio.js';\n", '')
  .replace("import { createDocumentController, documentIcons } from './itdocument.js';\n", '')
  .replace("import { createRichTextController, richTextToolbarMarkup, sanitizeRichHtml } from './itrichtext.js';\n", '')
  .replace('export function configureITranslator', 'function configureITranslator')
  .replace('export function setITranslatorTarget', 'function setITranslatorTarget')
  .replace('export function setITranslatorFont', 'function setITranslatorFont')
  .replace('export function setITranslatorFontSize', 'function setITranslatorFontSize')
  .replace('export class ITranslatorTextarea', 'class ITranslatorTextarea');

const css = await readFile('src/itextarea.css', 'utf8');
const config = await readFile('config/itrans-config.json', 'utf8');
const fontFiles = [
  'NotoSansDevanagari-Regular.ttf',
  'NotoSerifDevanagari-Regular.ttf',
  'TiroDevanagariSanskrit-Regular.ttf',
  'Sanskrit-2003-Font.ttf',
  'Sanskrit2020.otf',
  'Chandas_Font.ttf',
  'material-symbols-outlined.woff2',
  'OFL-Noto-Sans-Devanagari.txt',
  'OFL-Noto-Serif-Devanagari.txt',
  'OFL-Tiro-Devanagari-Sanskrit.txt',
  'LICENSE-Sanskrit-2003.txt',
  'LICENSE-Chandas-GPL-2.0.txt',
];

await mkdir('dist/fonts', { recursive: true });
await writeFile('dist/itarea.js', `/* iTranslator Text Area | generated by npm run build */\n${bundledEngine}\n${bundledAudio}\n${bundledDocument}\n${bundledRichText}\n${bundledComponent}\nexport { configureITranslator, setITranslatorTarget, setITranslatorFont, setITranslatorFontSize, createItareaArchive, readItareaArchive, sanitizeRichHtml, ITranslatorTextarea };\n`);
await writeFile('dist/itarea-standalone.js', `/* iTranslator Text Area standalone build | generated by npm run build */\n${bundledEngine}\n${bundledAudio}\n${bundledDocument}\n${bundledRichText}\n${bundledComponent}\nconfigureITranslator(${config.trim()});\n`);
await writeFile('dist/itarea.css', css.replaceAll('../fonts/', './fonts/'));
await writeFile('dist/itrans-config.json', config);
await writeFile('dist/itrans-config.js', `/* iTranslator Text Area configuration | generated by npm run build */\nexport default ${config.trim()};\n`);
await copyFile('THEMING.md', 'dist/THEMING.md');
await Promise.all(fontFiles.map(file => copyFile(`fonts/${file}`, `dist/fonts/${file}`)));
